name: Monitor and Notify

on:
  push:
    branches:
      - main

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run monitoring script
        id: monitor
        run: |
          chmod +x ./scripts/monitoring_script.sh
          ./scripts/monitoring_script.sh

      - name: Check for threats
        id: check_threats
        run: |
          if grep -q "threat_detected" ./scripts/monitoring_script_output.txt; then
            echo "::set-output name=threat_detected::true"
          else
            echo "::set-output name=threat_detected::false"
          fi

      - name: Send notification if threat detected
        if: steps.check_threats.outputs.threat_detected == 'true'
        run: |
          chmod +x ./scripts/notification_script.sh
          ./scripts/notification_script.sh
