name: Monitor and Notify

on:
  push:
    branches:
      - main

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run monitoring script
        id: monitor
        run: |
          chmod +x ./scripts/monitoring_script.sh
          ./scripts/monitoring_script.sh

      - name: Set commit history flag
        run: |
          if [ $(git rev-list --count HEAD) -le 1 ]; then
            echo "::set-output name=only_one_commit::true"
          else
            echo "::set-output name=only_one_commit::false"
          fi

      - name: Send notification if threat detected
        if: steps.monitor.outputs.threat_detected == 'true' && steps.monitor.outputs.only_one_commit == 'false'
        run: |
          chmod +x ./scripts/notification_script.sh
          ./scripts/notification_script.sh
