name: Monitor and Notify

on:
  push:
    branches:
      - main

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run monitoring script
        id: monitor
        run: |
          chmod +x ./scripts/monitoring_script.sh
          ./scripts/monitoring_script.sh

      - name: Send notification if threat detected
        if: ${{ steps.monitor.outputs.threat_detected == 'true' }}
        run: |
          chmod +x ./scripts/notification_script.sh
          ./scripts/notification_script.sh
